# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-product-apis"
client_id = "f3b68a748b937a4f38d5a1caf91a5ab9"
application_url = "https://maybe-leasing-cameron-people.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://maybe-leasing-cameron-people.trycloudflare.com/auth/callback",
  "https://maybe-leasing-cameron-people.trycloudflare.com/auth/shopify/callback",
  "https://maybe-leasing-cameron-people.trycloudflare.com/api/auth/callback",
  "https://maybe-leasing-cameron-people.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ashishtest-extendedvariants.myshopify.com"
